### PR TITLE
Decouple HTTP client + Add integration tests + Bugfix

### PR DESCRIPTION
**Pull request by tim-bezhashvyly**

### CODE REVIEW

**Comment by Moinax** [comment]
Hi @tim-bezhashvyly , before merging this pull request, can you make some changes :

* First, keep the library compatible with PHP 5.3 (I see some [] instead of array() )
* Then, I prefer keeping all methods and properties protected instead of private so we can easily override them if needed unless you see any issue keeping that way.

**Comment by tim-bezhashvyly** [comment]
There are couple more of tasty PHP 5.4 features I used:
 - `ClassName::class` instead of `"ClassName"`
 - `(new ClassName())->method()`

And PHP 5.3 so hopelessly old and if people will not see these new features in the code they will never start using them. However I do respect your striving for a backwards compatibility so final decision is of course up to you.

Private vs. protected is a old holly war. I'm on the side of private methods as a part of [SOLID](http://en.wikipedia.org/wiki/SOLID_%28object-oriented_design%29) programming principles. But again the decision is up to you.

Please let me know what do you think on both subjects.

**Comment by Moinax** [comment]
For the first point, I think there is a lot of PHP 5.3 running and I don't want to prevent anyone to be able to use the library. We can of course maintain two versions if we gain any performance using those new PHP 5.4 features.

For the second point, Iets keep them private for now, we will see if anyone encounter a problem having no extension capabilities.

Regards,

**Comment by tim-bezhashvyly** [comment]
Ok, now it's 5.3 compatible again.

**Comment by Moinax** [comment]
Great thanks @tim-bezhashvyly

**Pull request merged**
