### PR TITLE
switching from native http client to guzzlehttp client and php 5.6

### PR DESCRIPTION
**Pull request by darkmatus**
To get a more actual and better supportable client where changed the native client usage for a guzzlehhtp client. Also the required PHP version was changed to 5.6 because the lifetime of php 5.3 has runned out.
We have also changed the namespace to Emarsys.

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
First of all this is a pretty fundamental change which means this must be approved by @Moinax in any way. From my side I see no reason why Guzzle client can not live in parallel to native one. Also could you please tell what are the benefit of having Guzzle client in this repository?

**Comment by darkmatus** [comment]
At all the guzzle client was implemented becaus it is in use in our company and we want to have consistant clients used. The other part is that every one can pass his creadentials and won't need to create a client as self.

**Comment by Moinax** [comment]
Hi guys,

First of all, let me tell you that I left the Php world 4 years ago, so I don't know what are the best practices currently.

I think it's time that someone else take authority on this repository.

If it's still the most used Emarsys Php client and it's still referenced in the official documentation, maybe Emarsys should take the authorship if they have resources internally. 

In the meantime, @tim-bezhavshvyly maybe have you suggestions about this.

That being said, let's focus on the this PR:

Unless the best practices have changed, there is no reason to change the namespace unless the repository is moved to the Emarsys account.

Concerning the HttpClient I don't see why we would add a dependency on specific one. The goal here was to be dependency free and provide an easy way to use the HttpClient of your choice. If your company is heavily using Guzzle internally, my recommendation would be to create your own project (GuzzleEmarsys for example) and add a dependency on snowap/emarsys and build a pre-configured client with Guzzle as your HttpClient.
In that way, you will be able to reuse it everywhere you want without forcing the other users to install another dependency or break compatibility.

Regards

**Comment by Moinax** [comment]
By the way, if you look at this issue https://github.com/snowcap/Emarsys/issues/6 you'll see that Guzzle was used as a default HttpClient and Tim refactored this to get rid of it and let the users choose.

I still think it was a step in the right direction and won't recommend to change this.

Regards

**Comment by darkmatus** [comment]
Okay, actually I dont have the time to refactor it. So we will use internally our fork with my modifications :)

**Pull request closed without merging**
