### PR TITLE
Fix \Snowcap\Emarsys\Client::getContactId method

### PR DESCRIPTION
**Pull request by webarchitect609**
Correct return type annotation: integer;
More informative exception when something goes wrong;

Not just 'missing id' but real reason: http://joxi.ru/L21bjGf88b5lAX?d=1

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
I'm fine with this PR. The only question is if we should treat it as a BC breaking as in fact it is.

**Comment by webarchitect609** [comment]
Could you describe reasons why it is BC breaking?

**Comment by Moinax** [comment]
I won't say it's a breaking change as only the phpdoc was wrong, but the results was the same (cast excepted)

**Comment by tim-bezhashvyly** [comment]
Before method was returning string, now it is returning an integer. Client who depend on the return type will get an exception (or \TypeError in PHP7).

**Comment by webarchitect609** [comment]
OK. What if remove `(int)` typecasting? Just declare in phpDoc that it sould be an integer?

**Comment by tim-bezhashvyly** [comment]
I'm fine with both. Just in one case we have to rase a minor version and in another a major.

**Comment by Moinax** [comment]
I let you decide @tim-bezhashvyly

**Comment by tim-bezhashvyly** [comment]
Let's remove type casting as it also can be a reason of silent failure in case non-integer is casted. I would say in PHP 5.x type detection is a client responsibility.

**Comment by webarchitect609** [comment]
Ok. And leave `@return int`?

**Comment by tim-bezhashvyly** [comment]
Yes, please. This is valuable.

**Comment by webarchitect609** [comment]
Done. Please, check it :)

**Comment by tim-bezhashvyly** [comment]
Thank you for the commitment.

**Pull request merged**
