### PR TITLE
getEmailLaunches must POST

### PR DESCRIPTION
**Pull request by otzy**

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
Are you sure? The documentation seems to be inconsistent here. At page 19 it says POST but on page 74 - GET.

**Comment by otzy** [comment]
I've tested right now. It does not work with GET.
Also POST is here https://dev.emarsys.com/suite/emails/launch_list.html

**Comment by tim-bezhashvyly** [comment]
:+1:

**Comment by tim-bezhashvyly** [comment]
Even though logically it has to be GET.

**Comment by otzy** [comment]
yeah, there are many gets which are POSTs in API

**Pull request merged**
