### PR TITLE
update multiple contacts field mapping

### PR DESCRIPTION
**Pull request by otzy**

### CODE REVIEW

**Comment by tim-bezhashvyly** [comment]
How about introducing public `updateContacts` method which will call `updateContact`?

**Comment by otzy** [comment]
thought so too. It was just easier for me to use existing function.
Also doubted about usefulness. In the new function new parameters should be introduced as well - $key_id, $field_id, $source_id, $contacts. But anyway developer should know internals of Emarsys API data formats, so this will not significantly simplify development.

**Comment by tim-bezhashvyly** [comment]
Well, I was primary thinking about single responsibility.

**Comment by otzy** [comment]
I agree, but another thing is that it's not separated in the api too. So sdk conforms api :)

**Comment by tim-bezhashvyly** [comment]
Another questionable thing here is accessing variable by reference. Can be easily avoided.

**Comment by otzy** [comment]
$v is not reused outside foreach, so it can not be any side effect. On the contrary we are avoiding cloning of every contact, which in turn can be quite a big set of data.

**Comment by otzy** [comment]
I would also passed all these arrays to functions as references. It's worth only for createContact and updateContact though

**Comment by Moinax** [comment]
I am not very aware about how the Emarsys API is working with multiple contacts, but I like the idea of @tim-bezhashvyly to get a new method "updateContacts". It makes the thinks clearer on the client side and avoid the need to know the Emarsys API, which is one of the goal of creating this client (abstraction).

We can keep both principle if you like, but I am certainly more confortable with a dedicated method than passing a special key to a method named "updateContact".

**Comment by otzy** [comment]
updating and creating multiple contacts works good in general. But it throws errors if you try to send requests simultaneously from more than 3 threads. And sometimes their db connection goes down. So I decided not to overload them and send contacts in the single thread with small sleep after every request. Empiric safe amount of contacts exporting per hour is 70000.
So if someone needs more, it's better to look in the direction of csv.

**Comment by otzy** [comment]
I agree with the reasons for dedicated methods, but concern about parameters, because I use only keyId and array of contacts. And I did not test how other parameters work.
On the other hand other methods also provide very minimalistic abstraction level as they mostly accept only single array parameter and you have to read api reference in order to populate this array with correct data.
So why createContacts should behave differently?

**Comment by tim-bezhashvyly** [comment]
In my opinion readability is only one problem here.

Another issue is breaking of a single responsibility principle. The `updateContact` method is now conditionally doing two things. Having at least 4 paths of execution. Putting aside theoretical problems it significantly drops the testability of this method.

Also breaking the immutability of a `$contact` variable also doesn't look pretty.

**Comment by otzy** [comment]
ok, I agree with updateContacts.

still I don't see any problems with references here.
$data passed by value, so it's a clone. So changing it's members inside function, does not affect variables outside.
Do you think references were introduced in PHP only in order to avoid them?

**Comment by tim-bezhashvyly** [comment]
Currently its more about good practices. However there might be side effects if code will be executed in a multi-threaded environment like http://appserver.io or whatever else can come in future.

**Comment by otzy** [comment]
I'm not really in pthreads. But php reference is not a pointer, and again $contact is not global. And all these multi-threaded environments can be thread-safe (and appserver.io definitely is).
But I'm not sure.
So, can you make mapFieldsToIds() protected. Thus I can overwrite all functions where I pass big arrays, and use references inside them.

**Comment by tim-bezhashvyly** [comment]
I guess you are right about scope protection.

**Comment by otzy** [comment]
Hey guys, what about this pull request and other 2?
If you insist on getting rid of references I'm ok with that, but then it would be nice to change mapFieldsToIds() to protected.
Also if you think that multiple update/create should have separate methods, let me know which parameters you think these functions need.
We use composer and now snowcap/Emarsys library is modified a bit. So I'm anxious about the next composer update, that will probably screw up everything.

**Comment by Moinax** [comment]
Hi @otzy , sorry for the delay, I had a lot of personal stuff to handle these few months.

I merged all your PR as they don't break anything. There will be plenty of time to adapt this later if needed.

I will create a new release right now with all the PR merged.

Regards

**Pull request merged**
